### PR TITLE
Login: ISSUE

### PR DESCRIPTION
**Pull request by yohanology**
Hey,

When I try to login from the mobile app, I get this error:

```
Object {email: "yohansihou@gmail.com", password: "yohan123"}
ionic.bundle.js:19341 OPTIONS https://formidableforms.herokuapp.com/auth/sign_in 503 (Service Unavailable)

(index):1 XMLHttpRequest cannot load https://formidableforms.herokuapp.com/auth/sign_in. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 503.
controllers.js:25 

Object {reason: "unauthorized", errors: Array[1]}
errors: Array[1]
0: "Invalid credentials"
length: 1
__proto__: Array[0]
reason: "unauthorized"
__proto__: Object
```

Coul you help me please?

### CODE REVIEW

**Comment by h8rry** [comment]
You need to use https://github.com/cyu/rack-cors. Look at the Rails section, not Rack.

**Comment by h8rry** [comment]
The error is caused by `No 'Access-Control-Allow-Origin' header is present`

**Comment by yohanology** [comment]
I fixed it in the web app. Can you check the other PR please. Thanks!

**Comment by h8rry** [comment]
Does it work now?

**Comment by h8rry** [comment]
Looks good. Can merge.

**Comment by yohanology** [comment]
yes it works

**Comment by yohanology** [comment]
need to try on heroku if the environment variable works

**Pull request merged**
